### ISSUE TITLE
EmailComposer with attachments crash

### ISSUE THREAD

**Issue by brunogptavares** [purplecabbage/phonegap-plugins#124]
I'm getting a crash when my app it's returning from EmailComposer (Android) plugin. Sometimes it works others it crash. 

I think, it's android closing my app because lack of memory it shouldn't crash, but opening app again.

Thanks 

06-25 15:15:36.940: D/DroidGap(28017): Request code = 0
06-25 15:15:36.940: D/DroidGap(28017): We have a callback to send this result to
06-25 15:15:36.970: W/dalvikvm(28017): threadid=1: thread exiting with uncaught exception (group=0x40018578)
06-25 15:15:37.000: E/AndroidRuntime(28017): FATAL EXCEPTION: main
06-25 15:15:37.000: E/AndroidRuntime(28017): java.lang.RuntimeException: Unable to resume activity {pt.itds.app.mystreet/pt.itds.app.mystreet.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {pt.itds.app.mystreet/pt.itds.app.mystreet.MainActivity}: java.lang.NullPointerException
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2124)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2139)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1672)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.access$1500(ActivityThread.java:117)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.os.Looper.loop(Looper.java:130)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.main(ActivityThread.java:3687)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at java.lang.reflect.Method.invokeNative(Native Method)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at java.lang.reflect.Method.invoke(Method.java:507)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at dalvik.system.NativeStart.main(Native Method)
06-25 15:15:37.000: E/AndroidRuntime(28017): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {pt.itds.app.mystreet/pt.itds.app.mystreet.MainActivity}: java.lang.NullPointerException
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.deliverResults(ActivityThread.java:2536)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2111)
06-25 15:15:37.000: E/AndroidRuntime(28017):    ... 12 more
06-25 15:15:37.000: E/AndroidRuntime(28017): Caused by: java.lang.NullPointerException
06-25 15:15:37.000: E/AndroidRuntime(28017):    at org.apache.cordova.DroidGap.onActivityResult(DroidGap.java:850)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.Activity.dispatchActivityResult(Activity.java:3908)
06-25 15:15:37.000: E/AndroidRuntime(28017):    at android.app.ActivityThread.deliverResults(ActivityThread.java:2532)
06-25 15:15:37.000: E/AndroidRuntime(28017):    ... 13 more

**Comment by brunogptavares** [comment]
This was not a issue from EmailComposer, it was from cordova 2.4, https://issues.apache.org/jira/browse/CB-2533 and it's resolved in 2.9.
